### PR TITLE
Add build

### PR DESCRIPTION
**Pull request by bestguy**
- Add build using webpack
- Move “main” back to lib/index.js
- Add pre/post publish steps

### CODE REVIEW

**Comment by awinogradov** [comment]
Agree with @ljharb. Also, I think we can rewrite source for compatibility with node 8+ and we will not need build step.

**Comment by ljharb** [comment]
@awinogradov a build step will still be needed; enzyme supports far older than node 8 and its adapters should too.

**Comment by awinogradov** [comment]
From Enzymes `.travis.yml`
```yml
node_js:
  - "8"
  - "6"
  - "4"
```

So, we can write code for node 4+ :) It's not a big problem. Or if it is, we can use babel only, or TS. Last is better but not required. Webpack is too much here.

**Comment by ljharb** [comment]
I agree webpack is too much, but i think babel is appropriate. It’s hard to remember what node 4, or 6, años soon 8, supports - babel prevents mistakes.

**Comment by bestguy** [comment]
Sure, this was just a webpack config I quickly ported to fix this.
Feel free to close or I'll update in next week or so with a Babel approach

**Comment by awinogradov** [comment]
Solved in #7

**Comment by bestguy** [comment]
Thanks, can you publish a new build to npm?  I still see 0.1.0 which is broken, and I think keeps people away from this project

**Pull request closed without merging**
