### PR TITLE
Added Build, fixed dependencies

### PR DESCRIPTION
**Pull request by sanpoChew**
Can be installed through npm now direct from git

### CODE REVIEW

**Comment by awinogradov** [comment]
We don't need transpiled code in the repo. It's only for npm package.

**Comment by sanpoChew** [comment]
@awinogradov Yes that's true, I did this because I thought it hadn't been published on npm and I wasn't sure when it would be. But after doing another search it looks like it actually has been published, albeit under a different name: https://www.npmjs.com/package/enzyme-adapter-preact

I think that published package doesn't include the work done by you though?

**Comment by awinogradov** [comment]
Sorry for the delay! I returned back from vacation and ready to make something awesome ;)

So, I can't publish this package. We need to ask @aweary to do this or add me as a collaborator on npm.

**Comment by aweary** [comment]
@awinogradov what's your username on npm? I can add you. Also, if you delete your fork, I can just transfer this repo to your account.

**Comment by awinogradov** [comment]
O, sorry! It's different, yeah) It's historical mistake) @verybigman on npm

**Comment by kontrollanten** [comment]
Any news here? It would be really nice to use this adapter

**Comment by awinogradov** [comment]
@aweary can you add me to the list of collaborators on npm?

**Comment by aweary** [comment]
@awinogradov I've added you as an owner. Also, if you can remove your fork (assuming it doesn't delete any of your pending work) I can transfer the repo to your Github account as well.

**Comment by awinogradov** [comment]
> I can transfer the repo to your Github account as well.

@aweary nice! Thank you!

@sanpoChew can you remove transpiled files from your PR and we can merge it and release after that ;)

**Comment by sanpoChew** [comment]
@awinogradov just removed those and added a prepublish hook instead 👍

**Pull request merged**
