### PR TITLE
Add ES6 module build

### LINKED ISSUE #15: Export ES6-compatible build code
I can see that current code is mixing CommonJS and ES6 modules: https://github.com/aweary/enzyme-adapter-preact/blob/master/src/PreactAdapter.js

it also contains `module.exports` which always adds lots of pain when you try to integrate module like `enzyme-adapter-preact` into ES6-code project (or even TS). Usually it's considered a good practice to have named exports. Also it's worth it to have ES6 code in npm package + "module" property in package.json. I could've added it to package.json but I'm a bit afraid that I will break some plans on the package.

@aweary @awinogradov 🆙

### PR DESCRIPTION
**Pull request by 1999**
Close #15 
This is a breaking change

### CODE REVIEW

**Comment by awinogradov** [comment]
@1999 Thanks, man!

**Comment by 1999** [comment]
Wow, that was fast :) Are you okay with this API change btw?

**Comment by awinogradov** [comment]
Yep!) It hasn't published yet. Implemented version of adapter now in master, but not in npm. It's not major changes now

**Comment by 1999** [comment]
Btw maybe you have some ideas here. I'm trying to use `find(selector)` enzyme method for mounted component and it always returns an empty ReactWrapper. Can it be related to enzyme-adapter-preact implementation?

**Comment by awinogradov** [comment]
Maybe) Can make a PR with test for this case?

**Comment by 1999** [comment]
I will try

**Comment by awinogradov** [comment]
@1999 I think I found your test) https://github.com/aweary/enzyme-adapter-preact/commit/de2b22001b9e6f105da2509bcf92f81e593f1d6b

**Comment by 1999** [comment]
Not sure. I'm using full DOM rendering, so it's probably [this one](https://github.com/aweary/enzyme-adapter-preact/blob/master/__tests__/MountWrapper.spec.js#L3584).

According to docs on preactjs.com only mount() is supported now: https://preactjs.com/guide/unit-testing-with-enzyme

**Pull request merged**
